import Head from 'next/head'
import Link from 'next/link'
import React, { useEffect, useState } from 'react'
import {
    Card,
    CardBody,
    CardTitle,
    Table,
    CardSubtitle,
    Button,
} from "reactstrap";
// import axios from 'axios';
// import { toast, ToastContainer } from 'react-toastify'

const index = () => {
    // const [loadData, setLoadData] = useState([]);
    // useEffect(() => {
    //     getRoles()
    // }, [])

    // const getRoles = async () => {
    //     try {
    //         const { data } = await axios.get(`${process.env.NEXT_PUBLIC_API}/app_details?page=${currentPage}&${Math.random()}`);
    //         setLoadData(data.data)
    //         setTotalCount(data.dataCount);
    //         setResultPerPage(data.resultPerPage);
    //     } catch (error) {
    //         console.log(error)
    //     }
    // }

    // const style = { color: 'green', fontSize: '20px', cursor: 'pointer' }
    // const delStyle = { color: 'red', fontSize: '20px', cursor: 'pointer', marginLeft: '5px' }

    // const handleDelete = async (id) => {
    //     try {
    //         alert("Are Your Sure to Delete")
    //         const { data } = await axios.delete(`${process.env.NEXT_PUBLIC_API}/app_details_delete/${id}`);
    //         toast.success("App Deleted Successfully");
    //         getAppsDetails()
    //     } catch (error) {
    //         toast.error(error);
    //     }
    // }

    return (
        <div>
            <Head>
                <title>Apps List</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Card>
                <h2>Safawat Hossain </h2>
            </Card>
            {/* <Card>
                <CardBody>
                    <CardTitle tag="h5">Applications</CardTitle>
                    <CardSubtitle className="mb-2 text-muted" tag="h6">
                        <div className='d-flex justify-content-between'>
                            <h6> Quran Admin Web</h6>
                            <Link href="applications/create">
                                <Button className="btn" color="primary">
                                    Add Applications
                                </Button>
                            </Link>
                        </div>
                    </CardSubtitle>
                    <ToastContainer
                        position="top-right"
                        autoClose={2000}
                        hideProgressBar={false}
                        newestOnTop={false}
                        closeOnClick
                        rtl={false}
                        pauseOnFocusLoss
                        draggable
                        pauseOnHover
                    />
                    <div className="table-responsive">
                        <Table className="text-nowrap mt-3 align-middle" borderless={true}>
                            <thead>
                                <tr>
                                    <th>Sl</th>
                                    <th>Application</th>
                                    <th>Primary Topic</th>
                                    <th>Firebase Token</th>
                                    <th>App Url</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {loadData.map((data, key) => (
                                    <tr className="border-top" key={key}>
                                        <td>{key + 1}</td>
                                        <td>{data.name}</td>
                                        <td>{(data.primary_topic)}</td>
                                        <td>{(data.firebase_token).slice(0, 25)}</td>
                                        <td>{data.app_url}</td>
                                        <td>
                                            <i className="bi bi-pencil-square" style={style} onClick={() => router.push(`/applications/${data._id}`)}></i>
                                            <i className="bi bi-trash" style={delStyle} onClick={() => handleDelete(data._id)}></i>
                                        </td>

                                    </tr>
                                ))}
                            </tbody>
                        </Table>

                    </div>
                </CardBody>
                <CardBody>
                </CardBody>
            </Card> */}
        </div>
    )
}

export default index